### ISSUE TITLE
Launching application throws error

### ISSUE THREAD

**Issue by teesloane** [minimalchat/operator-app#47]
<img width="532" alt="screenshot 2017-06-23 18 43 07" src="https://user-images.githubusercontent.com/12987958/27502675-da53a958-5843-11e7-80cd-a4648ad40fc0.png">

error text:
```
Uncaught Exception:
Error: EROFS: read-only file system, open '/private/var/folders/pv/_7w_0czx4kj0z8ghg36dtt3c0000gq/T/AppTranslocation/228AF42A-449F-4FEF-B9F8-CEBCF58F7B17/d/Operator.app/Contents/Resources/app/config.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at EventEmitter.onSendConfig (/private/var/folders/pv/_7w_0czx4kj0z8ghg36dtt3c0000gq/T/AppTranslocation/228AF42A-449F-4FEF-B9F8-CEBCF58F7B17/d/Operator.app/Contents/Resources/app/Window.js:183:23)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/private/var/folders/pv/_7w_0czx4kj0z8ghg36dtt3c0000gq/T/AppTranslocation/228AF42A-449F-4FEF-B9F8-CEBCF58F7B17/d/Operator.app/Contents/Resources/electron.asar/browser/api/web-contents.js:247:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
```

**Comment by teesloane** [comment]
Addendum:

after clicking `OK`

the app opens.

sorry.

not sorry.

> it's still an issues
- mihok, 2017

**Comment by teesloane** [comment]
Also, it opens the dev tools. (lol we need environment variables)
